# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: star_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstar_data.proto\x12\x08mwm_msgs\"\x90\x01\n\x04Star\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttimestamp\x18\x08 \x01(\x05\x12\r\n\x05pos_x\x18\x02 \x01(\x01\x12\r\n\x05pos_y\x18\x03 \x01(\x01\x12\r\n\x05pos_z\x18\x04 \x01(\x01\x12\x11\n\tmagnitude\x18\x05 \x01(\x02\x12\r\n\x05\x62p_rp\x18\x06 \x01(\x02\x12\x11\n\x04name\x18\x07 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"<\n\x08StarData\x12\x1d\n\x05stars\x18\x01 \x03(\x0b\x32\x0e.mwm_msgs.Star\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\"3\n\x0b\x44\x61taRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x05\x12\x11\n\tnode_name\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'star_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STAR._serialized_start=30
  _STAR._serialized_end=174
  _STARDATA._serialized_start=176
  _STARDATA._serialized_end=236
  _DATAREQUEST._serialized_start=238
  _DATAREQUEST._serialized_end=289
# @@protoc_insertion_point(module_scope)
