model_name: orbit_mlp_DSN.pt

norm_path: "norms/orbit_norm_data_DSN.json"
val_data_path: "data/dataset_DSN/validation_data"
test_data_path: "data/dataset_DSN/test_data"
training_data_path: "data/dataset_DSN/training_data"

hidden_layers: [512, 512, 256, 256, 128]
epochs: 150 # Epochs per run
batch_size: 100000

use_half_precision: False # [True,False] loads training data into gpu at half precision, recasts to float on batch usage
use_dataloader: False # [True,False]
use_gradient_clipping: True
model_type: plain # [plain, residual, fourier, siren]

grad_clip_max_norm: 0.1
optimizer: adamW # [adam, adamW]


runs:
  1:  # plateau example
    training_data_filter: /orbit_train_part00[01234]*.npy # Can split data with filters
    min_learning_rate: 0.000001
    start_learning_rate: 0.001
    scheduler: plateau # [plateau, cosanneal]
    patience: 15  # Required for pleteau scheduler
    
  2:  # cosanneal example
    training_data_filter: /orbit_train_part00[!01234]*.npy
    min_learning_rate: 0.000001
    start_learning_rate: 0.001
    override_learning_rate: True # [True, False] resets optimizer LR to start_learning_rate
    scheduler: cosanneal # [plateau, cosanneal, cosannealwarmrestart]
    epochs: 50 # Can override epochs in this run
  
  3:  # cosannealwarmrestart example
    training_data_filter: /orbit_train_*.npy
    min_learning_rate: 0.000001
    start_learning_rate: 0.001
    override_learning_rate: True # [True, False] resets optimizer LR to start_learning_rate
    scheduler: cosannealwarmrestart # [plateau, cosanneal, cosannealwarmrestart]
    warm_restart_epochs: 50 # number of epochs in the first cycle before resetting LR
    warm_restart_cycle_mult: 1 # cycle length multiplier


