model_name: orbit_mlp_32.2.pt

norm_path: "norms/orbit_norm_data_13S.json"
val_data_path: data/dataset_13S/validation_data
test_data_path: data/dataset_13S/test_data
training_data_path: data/dataset_13S/training_data

hidden_layers: [512, 512, 256, 256, 128]
epochs: 600
batch_size: 102400

use_dataloader: False
use_gradient_clipping: False
data_dtype: bf16 # [fp16, fp32, bf16]

grad_clip_max_norm: 0.1
optimizer: adam # [adam, adamW]

runs:
  1:
    training_data_filter: /orbit_train_*.npy
    min_learning_rate: 0.000001
    start_learning_rate: 0.001
    scheduler: plateau
    patience: 15
